= Digital Signage
Benjamin Ecke, Daniel Andricic
1.0.0, 2020-11-04: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:github-square[link=https://github.com/2021-4ahif-syp/project-digitalsignage]
icon:home[link=https://htl-leonding-project.github.io/digitalsignage-on-demand/]
endif::backend-html5[]

== Entwurfsmuster Digital Signage On Demand Videos

Unsere Erweiterung soll das Anzeigen von
Videos und Fotos ermöglichen.

* Angular:
    Diese Erweiterung wird über einen Angular-Client gesteuert. +
    Der Angular Client wird auf einer Webseite mit NGINX betrieben. +
* Quarkus Server/Client

* Keycloak Server: +
    Damit nur berechtigte Benutzer auf die Benutzer-Steuerung kommen können soll der Keycloak Server +
    die Benutzer authentifizieren mittel OpenID. So können wir die Anmeldedaten von den Schulservern abfragen und mit der
    Benutzereingabe vergleichen.
* REST-Services: +
    Damit dieser Angular Client mit den Signage Server kommunizieren kann
    braucht er einen REST-Service. +
* XIBO-API: +
    XIBO-API wird mit den Angular-Client kommunizieren, damit das Aussehen
    dynamisch gestaltet wird. +
* NGINX-Webserver: +
    NGINX wird für den Webserver benutzt, weil es uns empfohlen wurde. +
* OpenID: +
    Die Authentifizierung wird mit OpenID erfolgen, so sollen auch nur
    authentifizierte Personen die Funktionen der Erweiterung nutzen können. +

== Aktivitätsdiagramm

Hier sieht man ein sehr stark vereinfachtes Aktivitätsdiagramm, um zu sehen, wie ungefähr +
die Auswahl eines Videos, funktionieren soll.

[plantuml,activityDiagram,png]
----
@startuml
skinparam linetype orthodox

(*) -right-> "Select Display"
"Select Display" -right-> "Select Media"
"Select Media" -right-> "Choose Time"
note right: Whole video or part of it.
"Choose Time" -down-> "Submit"
"Submit" --> (*)

@enduml
----

