= Meeting mit Halil and Prof. Stütz
 // Metadata
:author: Daniel Andricic
:date: 2021-02-15
:revision: 1.0
//Settings
:source-highlighter: coderay
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
// Refs:
:imagesdir: images
:sourcedir-code: digitalsigage-on-demand/digitalsignage
:toc:

Version: {revision}

++++
<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
++++

icon:github-square[link=https://github.com/htl-leonding-project/digitalsignage-on-demand]
icon:home[link=https://htl-leonding-project.github.io/digitalsignage-on-demand/]

[cols="3,3"]
|===
|Teilnehmer
|Anwesend
|Daniel Andricic
|icon:check[]
|Prof. Stütz
|icon:check[]
|Benjamin Ecker
|
|Halil Bahar
|icon:check[]
|===

== Was wurde besprochen?

Wir haben die Architektur unseres Xibo-Servers besprochen. +
Das erste, was wir tun müssen, ist ein neues Modul für unseren Xibo-Server zu erstellen. +
In diesem Modul würden wir die Funktionalität hinzufügen, dass der Server in der Lage ist, unseren
Befehl für ein neues Video sofort auszuführen zu können. +
Dieses Modul wird den Server zu einem Echtzeit-Server machen. +
Das bedeutet, dass der Server in der Lage wäre, so schnell wie möglich zu reagieren und er
würde die ganze Zeit auf neue Befehle warten. +

==== Xibo-Modul

Um ein solches Modul zu erstellen, müssen wir uns die Grundlagen in Javascript und PHP ansehen. +
Sobald dieses Modul fertig ist, kann es als Modul in den Xibo-Server implementiert werden. +
In diesem Modul wollen wir ein Overlay-Layout erstellen, das ständig im Hintergrund aktiv ist. +
Das Layout soll nur in den Vordergrund geholt werden, wenn ein Video abgespielt wird.

Die Videos werden im System mit dem Tag-Modul-on-demand getaggt. +
Auf diese Weise können wir alle Videos herausfiltern, die für die Wiedergabe geeignet sind. +
Die einzelnen Videos befinden sich bereits auf dem Server, sodass der Client +
keine Videos hochladen kann.

Wenn ein Video gestartet wird, soll das Modul dem Quarkus-Server mitteilen, dass ein Video abgespielt wird. +
Der Quarkus-Server sollte sich den Namen des Videos merken, wenn es gestartet wird.

Am Ende des Gesprächs wurde diskutiert, ob nur Youtube-Links +
oder Videos vom Server verwendet werden sollen.

==== Ergebnis

In diesem Gespräch konnten wir die Vorgehensweise für den Quarkus-Server und den Xibo-Server besprechen. +
Wir können von hier aus ohne Hilfe ein Modul erstellen, das wir anschließend in den Xibo-Server einbinden werden. +
Allerdings können wir keinen Termin in kürze bestimmen, da wir noch recherchieren müssen wie man ein Modul erstellt und +
in den Server implementiert. +
Wenn etwas unklar ist/wird, werden wir uns natürlich Hilfe holen.






