= Project assignment
Daniel Andricic Benjamin Ecker
1.0.0, 2020-10-08: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left

//Need this blank line after ifdef, don't know why...
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
endif::backend-html5[]

== Projectname

Digital Signage - On Demand Videos

== Project Client

Prof. Mag. Dr. Stütz

== Project Background

In our school, we have a huge Monitor in the auditorium. This monitor is mostly used for current news, weather service and to present new projects in the school.
To be able to show videos on this monitor quickly and easily, the goal would be an app
which streams the desired video to the display.
This would be used to show videos that represent or promote the school at the open day.

==== Purpose of the project
* Stream videos and fotos on display
* Project Presentation

==== Pre-Project

Since our project is an extension to a former diploma thesis, we
have already given a template and for this thesis we should create a client
that can access the CMS (Content-Management-System).

== Project Final Result

The end result is a web application with a built-in Angular Client that
accesses the existing REST functionalities of the Home DS (Digital Signage - Server).
This extension is supposed to send the videos/photos to be streamed to the signage server
via a rest client and display them on the monitor.
By authenticating the individual users via OpenID, only authorized persons should
be able to access the system.


== Project Deliverables

The project client gets a webapp that offers the possibility to stream photos and videos
to the monitor in the auditorium.
Only authorized persons can access these functions, this function
is provided by OpenID.
OpenID provides that the user only needs to authenticate once.

== Milestones

|===
|Milestone |Description

|Integration of Insomnia.
|Tested the user-permission on the signage-server.
|NGINX Webserver configured.
|Configured the NGINX-Server.
|Angular-Client ready to test.
|The Front-End is ready to test and is working on the Webserver.
|REST-Service configured and working.
|Implemented REST-Service.
|Xibo API implemented in the client.
|Tested the REST-Service function.
|OpenID configured.
|Access the server without re-authentication
|===

== Projectstart

Tbd, 2 weeks after the determination.

== Projectend

28.06.2021

== Technologies

* Nginx
* Angular
* REST
* Xibo
* OpenID (Authentication)
* Insomnia (Testing)

== Project Risks

* Implementation time too short
* Frameworks never used or no previous knowledge available.
* Webapp not compatible with the working infrastructure.

== Project Members

* Benjamin Ecker
* Daniel Andricic