= Meeting mit Halil
 // Metadata
:author: Daniel Andricic
:date: 2021-02-15
:revision: 1.0
//Settings
:source-highlighter: coderay
:icons: font
//:sectnums:    // Nummerierung der Überschriften / section numbering
// Refs:
:imagesdir: images
:sourcedir-code: digitalsigage-on-demand/digitalsignage
:toc:

Version: {revision}

++++
<link rel="stylesheet"  href="http://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
++++

icon:github-square[link=https://github.com/htl-leonding-project/digitalsignage-on-demand]
icon:home[link=https://htl-leonding-project.github.io/digitalsignage-on-demand/]

[cols="3,3"]
|===
|Teilnehmer
|Anwesend
|Daniel Andricic
|icon:check[]
|Benjamin Ecker
|icon:check[]
|Halil Bahar
|icon:check[]
|===

== Was wurde besprochen?

Wir haben die Vorgehensweise für die Ausführung eines Videos besprochen. +
Dabei haben wir uns geeinigt, dass wir kein XIBO-Modul erstellen müssen, sondern es reicht wenn +
wir das Video mit einem Embedded-Code ausführen, der beim Quarkus-Server am Ende nachfragt, ob +
das Video schon einmal ausgeführt wurde, falls ja, dann sollte das Layout entfernt werden. +

Wir haben uns auch geeinigt, dass wir am Anfang, nur die Requests an den XIBO-Server, in Quarkus implementieren.

==== Quarkus-Server

Der Quarkus-Server soll über REST-API mit dem XIBO-Server kommunizieren, ob gerade ein +
Video gestartet wurde oder ob alles nach den Schedules ausgeführt wird. +
Der Quarkus-Server soll für den Anfang nur GET-Requests beherrschen. +
Da wir am Anfang die meisten Daten vom XIBO-Server holen müssen. +
Beispielweise wir brauchen einen Monitor aus der Liste, ein Video der +
auf den XIBO-Server gespeichert ist und die Zeit wie lange das Video und wann es angezeigt werden soll. +

Wir haben ein sehr stark vereinfachtes Aktivitätsdiagramm erstellt, welches ungefähr den Vorgang +
beim Anzeigen eines Videos, im Hintergrund, passiert. +
link:concept.adoc[Entwurfsmuster] +

==== XIBO-Server


