= Digital Signage On-Demand-Videos
Benjamin Ecker, Daniel Andricic
1.0.5, 2020-11-04: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:github-square[link=https://github.com/htl-leonding-project/digitalsignage-on-demand]
icon:home[link=https://htl-leonding-project.github.io/digitalsignage-on-demand/]
endif::backend-html5[]

== Pflichtenheft Digital Signage On-Demand-Videos

=== Ausgangssituation

Die HTL Leonding ist eine berufsbildende Lehranstalt im oö. Zentralraum. +
Auf den Monitoren, die in der Aula stehen, werden aktuelle Nachrichten angezeigt. +
Es werden Nachrichten wie z.B. Wetter, Technik-Foren und aktuelle Nachrichten von
der Schule, Warnungen, etc. angezeigt. +
Auf den Monitoren werden auch Fotos dargestellt die meistens von den Schulprojekten +
bzw. Schulturnieren angezeigt werden.

=== Istzustand

In der Aula befinden sich 4 große Monitore. +
Die Monitore werden mit einer Software so gesteuert, dass man bestimmte Inhalte auf den Monitoren anzeigen kann. +
Die Software welche die Monitore verwaltet, verbindet sich mit einem der schulinternen Server, der über XIBO eine zeitgesteuerte +
Oberfläche mit täglichen Nachrichten anzeigt. +
Das ODROIDTV(Android TV in der Aula) ladet sich so alle nötigen Daten vom Server. +

=== Problemstellung

Derzeit kann der Digital-Signage Server keine On-Demand Videos streamen/zur Verfügung stellen. +
Die Software die den Digital-Signage Server(Xibo API) steuert, ist nicht echtzeit-basierend, somit +
kann eine Anfrage auf den Server nicht sofort ausgeführt werden. +
Aktuell sind alle Events, sheduled. +
Das bedeutet, dass alles was auf den Monitore/n angezeigt wird, ist schon im voraus geplant geworden.
So kann der Direktor beispielsweise am Tag der offenen Tür keine Videos auf die Monitore +
darstellen lassen.

=== Aufgabenstellung

Die Erweiterung soll den Digital-Signage Server so erweitern, dass man +
auch Videos beliebig auf einen oder mehreren ausgewählten Monitoren, anzeigen. +
Der Benutzer soll über der App ein Video auswählen, um es +
an den ausgewählten Monitor anzuzeigen. +
Um diese Funktionalität auch ohne Wartezeiten zu ermöglichen, soll ein Xibo-Modul erstellt werden, der +
den Digital-Signage Server zu einem Echtzeit-Server umwandelt.

==== Funktionale Anforderungen

* Videos anzeigen
* Monitor auswählen
* Video auswählen

==== Nichtfunktionale Anforderungen (NFA)

[plantuml, usecase-diagram, png]
----
@startuml
left to right direction

actor User as u

package "Digital Signage Erweiterung" {
    usecase "Login with School-ID" as sid
    usecase "Show video" as stv
    usecase "Select specific monitor" as slm
    usecase "Select specific video" as slv
}

u --> stv
stv .> slm : <<include>>
stv .> slv : <<include>>
stv .> sid : <<extends>>
@enduml
----

* Die Erweiterung soll nach drei Fehlversuchen die Anmeldung für 30 Sekunden blockieren. +
* Das System soll so effizient wie möglich die Ressourcen verwalten. +
* Es soll aufkommende Fehler in eine Log-Datei speichern. +
* Wartbarkeit. +
* Benutzerfreundlichkeit +
* Effizienz. +

=== Ziele

Das Ziel des Projekts, ist eine Web-Applikation mit einem +
Angular Client, der auf die bestehenden REST-Funktionalitäten des Digital-Signage Server zugreift. +
Die Erweiterung soll die zu anzuzeigenden Videos auf den ausgewählten Monitor sofort anzeigen. +
Durch die Authentifizierung der Benutzer über den Keycloak-Server (OpenID) sollen autorisierte Personen +
auf das System zugreifen können. +
Die Erweiterung der Xibo-API durch ein selbst gefertigtes Modul soll die Durchführung neuer Befehl sofort ermöglichen. +
Somit wird der Signage-Server durch dieses Modul zum Echtzeit-Server. +

=== Mengengerüst

Die Schule hat mehr als 1000 Schüler. +
Falls ein Lehrer ein Video vom Handy auf den Monitor +
anzeigen möchte, kann er/sie die verfügbaren Monitore +
auswählen und bestimmte Videos auswählen und somit +
einen Vortrag am Tag der offenen Tür oder sonstiges, halten. +

=== Rahmenbedingungen
Nicht vorgegeben

== Entwurf
=== Systemarchitektur
[plantuml,systemArchtecture,png]
----
@startuml
skinparam linetype orthodox


node "Signage Server" {
    [CMS]
    [XIBO API]
}

node "NGINX Server" {
    [Angular Client]
}

circle REST as r1
circle REST as r2

node "Quarkus Server" {
    [REST-Services]
}

node "Keycloak Server" {
    [OpenId-Service]
}


[XIBO API] <-- r1
[REST-Services] -left-> r1
[OpenId-Service] -right-> [REST-Services]
[OpenId-Service] -up-> [Angular Client]
[XIBO API] -right-> [CMS]
[Angular Client] --> r2
r2 --> [REST-Services]

@enduml
----

== Startseite

link:./index.html[Startseite] +
link:./project_proposal.html[Projektauftrag] +
link:./project_assignment.html[Projektantrag] +
link:./xibo-tutorial.html[XIBO-Tutorial] +
link:./system-specification.html[Pflichtenheft] +
link:./first_meeting.html[First Meeting] +
link:./concept.html[Entwurfsmuster] +
