= Digital Signage
Benjamin Ecke, Daniel Andricic
1.0.0, 2020-11-04: Some notes
ifndef::imagesdir[:imagesdir: images]
//:toc-placement!:  // prevents the generation of the doc at this position, so it can be printed afterwards
:sourcedir: ../src/main/java
:icons: font
:sectnums:    // Nummerierung der Überschriften / section numbering
:toc: left
ifdef::backend-html5[]

// https://fontawesome.com/v4.7.0/icons/
icon:github-square[link=https://github.com/2021-4ahif-syp/project-digitalsignage]
icon:home[link=https://github.com/2021-4ahif-syp]
endif::backend-html5[]

== Pflichtenheft Digital Signage On Demand Videos

=== Ausgangssituation

Die HTL Leonding ist eine HTL im oö. Zentralraum mit ca. 1000 Schülern und
den Fachabteilungen Medientechnik, Informatik. +
Sie besitzen einen großen Monitor in der Aula. +
Auf diesen Monitor werden aktuelle Nachrichten angezeigt. +
Es werden Nachrichten wie z.B. Wetter, Technik-Foren, aktuelle Nachrichten von
der Schule, Warnungen, etc. +
Auf den Monitor werden auch Fotos dargestellt die meistens von die Schulprojekte
bzw. Schulturniere angezeigt werden.

=== Istzustand
Der Monitor wird mit einer Software so gesteuert, dass man bestimmte Inhalte auf den Monitor anzeigen kann. +
Die Software die den Monitor verwaltet, verbindet sich mit den schulinternen Server der über XIBO eine geordnete
Oberfläche anzeigt. +
Der Monitor holt sich so alle nötigen Daten mit den REST-Services vom Server. +
Sobald man über der Webseite/App einen Befehl sendet, um beispielsweise ein Foto
anzuzeigen, sendet die App den Befehl an den Server über die
eingebauten REST-Services, der dann an den Signage-Server die Nachricht
weiterleitet. +
Anschließend sendet der Signage-Server eine Push-Benachrichtigung
an den ODROID TV (Monitor in der Aula), der dann am Ende das Foto anzeigt.

=== Problemstellung

Derzeit kann der Digital Signage Server keine On-Demand Videos streamen/zur Verfügung
stellen. +
Deshalb ist unsere Aufgabe eine Erweiterung für den DS-Sever (Digital Signage)
zu schreiben. +
Die Erweiterung soll das Anzeigen von beliebigen Videos/Fotos ermöglichen, so soll beispielsweise der Direktor
einen Vortrag halten können ohne die Funktionsweise des DS-Servers vollständig verstehen zu müssen.

=== Aufgabenstellung

Die Erweiterung soll den Digital-Signage Server so erweitern, dass man auch Videos
beliebig uploaden kann. +
Der Benutzer soll über der Webseite ein Video/Foto auswählen, um es an den jeweiligen Monitor anzuzeigen.


==== Funktionale Anforderungen
Unsere Erweiterung soll das Anzeigen von
Videos und Fotos ermöglichen.

* Angular:
            Diese Erweiterung wird über einen Angular-Client gesteuert. +
            Der Angular Client wird auf einer Webseite mit NGINX betrieben. +
* Quarkus Server/Client

* Keycloak Server: +
            Damit nur berechtigte Benutzer auf die Benutzer-Steuerung kommen können soll der Keycloak Server +
            die Benutzer authentifizieren mittel OpenID. So können wir die Anmeldedaten von den Schulservern abfragen und mit der
            Benutzereingabe vergleichen.
* REST-Services: +
            Damit dieser Angular Client mit den Signage Server kommunizieren kann
            braucht er einen REST-Service. +
* XIBO-API: +
            XIBO-API wird mit den Angular-Client kommunizieren, damit das Aussehen
            dynamisch gestaltet wird. +
* NGINX-Webserver: +
            NGINX wird für den Webserver benutzt, weil es uns empfohlen wurde. +
* OpenID: +
            Die Authentifizierung wird mit OpenID erfolgen, so sollen auch nur
            authentifizierte Personen die Funktionen der Erweiterung nutzen können. +

==== Nichtfunktionale Anforderungen (NFA)

[plantuml, usecase-diagram, png]
----
@startuml
left to right direction

actor User as u

package "Digital Signage Erweiterung" {
    usecase "Login with School-ID" as sid
    usecase "Show video/photo on a specific monitor" as stv
}

u --> stv
stv .> sid : <<include>>

@enduml
----

* Die Erweiteung soll nach drei Fehlversuchen die Anmeldung für 30 Sekunden blockieren. +
* Das System soll so effizient wie möglich die Ressourcen verwalten. +
* Es soll aufkommende Fehler in eine Log-Datei speichern. +
* Wartbarkeit. +
* Benutzerfreundlichkeit +
* Effizienz. +

=== Ziele

Das Ziel des Projekts, wäre eine Web-Applikation mit einem
Angular Client, der auf die bestehenden REST-Funktionalitäten des Home DS (Digital Signage - Server) zugreift.
Diese Erweiterung soll die zu streamenden Videos über einen Rest-Client von dem Signage-Server progressiv uploaden
und auf dem Monitor anzeigen. Durch die Authentifizierung der Benutzer über OpenID sollen autorisierte Personen
auf das System zugreifen können.

=== Mengengerüst

Die Schule hat mehr als 1000 Schüler, falls Lehrer
ein Video vom Handy auf den Monitor
anzeigen möchten, können Sie sich mit den
Digital Signage Monitor verbinden und effizient
einen Vortrag am Tag der offenen Tür oder sonstiges, halten. +

=== Rahmenbedingungen
Noch nicht vorgegeben

== Entwurf
=== Systemarchitektur
[plantuml,systemArch,png]
----
@startuml
node "Signage Server" {
    [CMS]
    [XIBO API]
}

node "NGNIX Server" {
    [Angular Client]
}

node "Quarkus Server" {
    [REST-Services]
}

node "Keycloak Server" {
    [OpenId-Service]
}

[XIBO API] <-- REST
[REST-Services] -left-> REST
[OpenId-Service] -up-> [REST-Services]
[OpenId-Service] -up-> [Angular Client]
[XIBO API] -right-> [CMS]
[Angular Client] -left-> [REST-Services]


@enduml
----

== Startseite

link:../../README.md[Startseite] +
link:./index.html[Index] +
link:./project_proposal.html[Projekauftrag]

